### ISSUE TITLE
error in getting session after update npm!

### ISSUE THREAD

**Issue by sajaddp** [spearmootz/node-laravel-session#6]
Hello,
I get error in getting session after update npm!
My code:
`
let headersCookie = cookie.parse(socket.request.headers.cookie);
if(headersCookie.hasOwnProperty('my_session')){
	session = headersCookie['my_session'];
	sessionLaravel = nodeLaravelSession.getSessionKey(session, laravelKey);
`
"laravelKey" is APP_KEY in .env.

Error:

> D:\xampp\htdocs\xxx\core\node_modules\php-unserialize\php-unserialize.js:54
      throw new window[type](msg, filename, line);
      ^
SyntaxError: Unknown / Unhandled data type(s): <
    at error (D:\xampp\htdocs\xxx\core\node_modules\php-unserialize\php-unserialize.js:54:13)
    at _unserialize (D:\xampp\htdocs\xxx\core\node_modules\php-unserialize\php-unserialize.js:166:11)
    at unserialize (D:\xampp\htdocs\xxx\core\node_modules\php-unserialize\php-unserialize.js:173:10)
    at Object.getSessionKey (D:\xampp\htdocs\xxx\core\node_modules\node-laravel-session\index.js:46:16)
    at Namespace.<anonymous> (D:\xampp\htdocs\xxx\core\serverHandler.js:59:43)

Laravel Version: 5.3.31
NodeJs Version: 6.10.3

**Comment by sajaddp** [comment]
I downgraded from version 1.0.8 to 1.0.7 and problem fixed!

**Comment by spearmootz** [comment]
thank you for bringing this up!!!! i know what the problem is :)

would you mind updating to 1.0.10 and letting me know if the issue is resolved?

**Comment by sajaddp** [comment]
Thanks @spearmootz 
The problem has been solved.

**Comment by spearmootz** [comment]
thanks for letting me know! i had not time to test in a local environment
